// controllers/dataController.js
import Survey from '../models/surveyModel.js';

/* ------------------- CRUD ------------------- */
export async function createEntry(req,res,next){ try{ const doc = await Survey.create(req.body); res.status(201).json(doc);} catch(e){next(e);} }
export async function getAllEntries(req,res,next){ try{ const q={}; const {state,year,indicator,group} = req.query; if(state) q.state=state; if(year) q.year=Number(year); if(indicator) q.indicator=indicator; if(group) q.group=group; const rows=await Survey.find(q).limit(1000); res.json(rows);} catch(e){next(e);} }
export async function getEntryById(req,res,next){ try{ const doc=await Survey.findById(req.params.id); if(!doc) return res.status(404).json({error:'Not found'}); res.json(doc);} catch(e){next(e);} }
export async function updateEntry(req,res,next){ try{ const doc=await Survey.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true}); if(!doc) return res.status(404).json({error:'Not found'}); res.json(doc);} catch(e){next(e);} }
export async function deleteEntry(req,res,next){ try{ const doc=await Survey.findByIdAndDelete(req.params.id); if(!doc) return res.status(404).json({error:'Not found'}); res.json({deleted:true,id:doc._id}); } catch(e){next(e);} }

/* ------------------- Eight HW1 Questions ------------------- */
export async function q1_count(req,res,next){ try{ const n = await Survey.countDocuments(); res.json({ question: 'How many survey responses are included in this dataset?', answer: n }); } catch(e){next(e);} }
export async function q2_years(req,res,next){ try{ const years = await Survey.distinct('year'); years.sort((a,b)=>a-b); res.json({ question: 'Which year(s) does this data cover?', answer: years }); } catch(e){next(e);} }
export async function q3_groups(req,res,next){ try{ const groups = await Survey.distinct('group'); res.json({ question: 'What kinds of groups were measured?', answer: groups }); } catch(e){next(e);} }
export async function q4_stateCount(req,res,next){ try{ const states = await Survey.distinct('state', { state: { $ne: 'United States' } }); res.json({ question: 'How many states reported data in this sample?', answer: states.length, detail: states }); } catch(e){next(e);} }
export async function q5_statesMostEntries(req,res,next){ try{ const agg = await Survey.aggregate([ { $match: { state: { $ne: 'United States' } } }, { $group: { _id: '$state', count: { $sum: 1 } } }, { $sort: { count: -1, _id: 1 } } ]); res.json({ question: 'Which states reported the most survey data entries?', answer: agg }); } catch(e){next(e);} }
export async function q6_stateSingleMax(req,res,next){ try{ const doc = await Survey.findOne({ state: { $ne: 'United States' } }).sort({ value: -1 }).select('state value indicator year'); res.json({ question: 'Which state reported the single highest percentage?', answer: doc?.state ?? null, value: doc?.value ?? null, indicator: doc?.indicator ?? null, year: doc?.year ?? null }); } catch(e){next(e);} }
export async function q7_stateAvgMax(req,res,next){ try{ const agg = await Survey.aggregate([ { $match: { state: { $ne: 'United States' } } }, { $group: { _id: '$state', avgValue: { $avg: '$value' } } }, { $sort: { avgValue: -1, _id: 1 } }, { $limit: 1 } ]); const top = agg[0] || null; res.json({ question: 'On average, which state reported the highest prevalence?', answer: top? top._id : null, value: top? top.avgValue : null }); } catch(e){next(e);} }
export async function q8_nationalVsStates(req,res,next){ try{ const natAgg = await Survey.aggregate([ { $match: { state: 'United States' } }, { $group: { _id: null, natAvg: { $avg: '$value' } } } ]); const statesAgg = await Survey.aggregate([ { $match: { state: { $ne: 'United States' } } }, { $group: { _id: null, statesAvg: { $avg: '$value' } } } ]); const nat = natAgg[0]?.natAvg ?? null; const states = statesAgg[0]?.statesAvg ?? null; let comparison = null; if (nat!=null && states!=null){ comparison = nat > states ? 'higher' : nat < states ? 'lower' : 'equal'; } res.json({ question: 'Are national averages higher or lower than the average of all states combined?', nationalAverage: nat, statesAverage: states, comparison }); } catch(e){next(e);} }
